<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;

class Test2Controller extends AppController {
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('RequestHandler');
    }

    public function index() {
        $this->autoRender = false;
        $this->response->withType('json');

        $tests = TableRegistry::get('Tests');
        $query = $tests->findByName('Mark');
        $resuts = $query->all();
        $this->set('tests', $resuts);
        $this->set('_serialize', ['tests']);

        $json = json_encode($resuts);
        echo $json;
        return;
    }

    public function create() {
        $this->autoRender = false;
        $this->response->withType('json');

        $tests = TableRegistry::get('Tests');
        $test = $tests->newEntity();
        $test->name = '柏餅';
        $test->aaaa = 78;
        $tests->save($test);

        echo $test;
        return;
    }

    public function update() {
        $this->autoRender = false;
        $this->response->withType('json');

        $tests = TableRegistry::get('Tests');
        $test = $tests->get(7);
        $test->aaaa = 690;
        $tests->save($test);

        echo json_encode($test);
        return;
    }
}