<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;

class Test2Controller extends AppController {
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('RequestHandler');
    }

    public function index() {
        $this->autoRender = false;
        $this->response->withType('json');

        $tests = TableRegistry::get('Tests');
        $query = $tests->findByName('Mark');
        $resuts = $query->all();
        $this->set('tests', $resuts);
        $this->set('_serialize', ['tests']);

        $json = json_encode($resuts);
        echo $json;
        return;
    }

    public function create() {
        $this->autoRender = false;
        $this->response->withType('json');
        $tests = TableRegistry::get('Tests');
        $query = $tests->query();
        $query->insert(['name', 'aaaa'])
            ->values([
                'name' => '佐々木小次郎',
                'aaaa' => 898
            ])
            ->execute();
    }

    public function update() {
        $this->autoRender = false;
        $this->response->withType('json');

        $tests = TableRegistry::get('Tests');
        $query = $tests->query();

        $query->update()
            ->set(['name' => 'ティナ・ターナー'])
            ->where(['id' => 4])
            ->execute();
    }
}